# Generated by Django 4.2.21 on 2025-06-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("direccion", models.TextField()),
                ("contacto", models.CharField(max_length=100)),
                ("partnership_activa", models.BooleanField(default=False)),
            ],
        ),
    ]
